name: custom_checkout_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  device_preview: ^1.2.0
  font_awesome_flutter: ^10.8.0
  flutter_credit_card: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/utils/
  filename: assets.dart
  field_prefix: